export enum APPOINTMENT_STATUS {
  OPEN = "OPEN",
  RESERVED = "RESERVED",
  CONFIRMED = "CONFIRMED",
  CANCELLED = "CANCELLED",
}

export const APPOINTMENT_STATUS_LABEL: { [key in APPOINTMENT_STATUS]: string } = {
  [APPOINTMENT_STATUS.OPEN]: "Aberto",
  [APPOINTMENT_STATUS.RESERVED]: "Reservado",
  [APPOINTMENT_STATUS.CONFIRMED]: "Confirmado",
  [APPOINTMENT_STATUS.CANCELLED]: "Cancelado",
}